function mazeResolver(maze) {
    return maze.map((row, rowIndex) => row.split('').map((col, colIndex) => {}))
}


function pathFinder(maze) {
    return true;
}

pathFinder(`......
......
......
......
......
......`)